apiVersion: v1
kind: Service
metadata:
  name: {{ include "smc-trading-agent.fullname" . }}
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "smc-trading-agent.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      protocol: {{ .Values.service.ports.http.protocol }}
      name: http
    - port: {{ .Values.service.ports.metrics.port }}
      targetPort: {{ .Values.service.ports.metrics.targetPort }}
      protocol: {{ .Values.service.ports.metrics.protocol }}
      name: metrics
  selector:
    {{- include "smc-trading-agent.selectorLabels" . | nindent 4 }}